data_dir: "data"

recompute:
  load_clean_tokenize: false
  embed: false
  merge_dislikes: false
  sentiment: false
  features: true
  train: true

classification_type: "multiclass"    # "binary" or "multiclass"
use_smote: false
models:
  - random_forest
  - gradient_boosting
  - xgboost
